<?php
define('_TOOLBARBUTTONS_CODESBEFOREDEFAULT','デフォルトツールバーの前に挿入するコード');
define('_TOOLBARBUTTONS_CODESAFTERDEFAULT','デフォルトツールバーの後ろに挿入するコード');
define('_TOOLBARBUTTONS_ADDITIONALSCRIPTS','追加のJavaScript');
define('_TOOLBARBUTTONS_BUTTONTYPE','ボタンの種類');
define('_TOOLBARBUTTONS_ADDTAGS','選択中の前後にタグ等を挿入する');
define('_TOOLBARBUTTONS_INSERTTEXT','カーソル位置にテキスト等を挿入する');
define('_TOOLBARBUTTONS_CODEBEFORE','前に挿入するコード');
define('_TOOLBARBUTTONS_BOTHAB','AB共');
define('_TOOLBARBUTTONS_CODEAFTER','後ろに挿入するコード');
define('_TOOLBARBUTTONS_AONLY','Aのみ');
define('_TOOLBARBUTTONS_TIP','ツールバーチップ');
define('_TOOLBARBUTTONS_BUTTONCAPTION','ボタン表示');
define('_TOOLBARBUTTONS_CREATECODE','コードを生成');
define('_TOOLBARBUTTONS_ADDBEFORE','前に追加');
define('_TOOLBARBUTTONS_ADDAFTER','後ろに追加');
define('_TOOLBARBUTTONS_ERROR_NOCAPTION','『ボタン表示』の入力がありません!');
?>